name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install crun dependencies
        run:
          sudo apt-get install -y make git gcc build-essential pkgconf libtool \
          libsystemd-dev libcap-dev libseccomp-dev libyajl-dev \
          go-md2man libtool autoconf python3 automake
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
